sonar.projectKey=runway
sonar.projectName=Runway
sonar.sourceEncoding=UTF-8

sonar.sources=app,config,db,lib
sonar.tests=test

sonar.exclusions=bin/**,vendor/**,storage/**,tmp/**
sonar.test.inclusions=test/**/*_test.rb

sonar.ruby.coverage.reportPaths=coverage/coverage.json
sonar.testExecutionReportPaths=tmp/sonar/test-execution.xml
